-- Audit Fixes SQL
-- Generated by autonomous audit on 2026-03-15
-- These policies were verified as already existing or were applied in prior sessions.

-- Authenticated read policies (already applied):
-- CREATE POLICY "Authenticated read parcels" ON public.parcels FOR SELECT TO authenticated USING (true);
-- CREATE POLICY "Authenticated read industrial parks" ON public.industrial_parks FOR SELECT TO authenticated USING (true);
-- CREATE POLICY "Authenticated read zoning" ON public.zoning_districts FOR SELECT TO authenticated USING (true);
-- CREATE POLICY "Authenticated read flood zones" ON public.flood_zones FOR SELECT TO authenticated USING (true);
-- CREATE POLICY "Authenticated read infrastructure" ON public.infrastructure_assets FOR SELECT TO authenticated USING (true);

-- User-scoped policies (already applied):
-- CREATE POLICY "Authenticated users manage own projects" ON public.projects FOR ALL TO authenticated USING (created_by = auth.uid()) WITH CHECK (created_by = auth.uid());
-- CREATE POLICY "Authenticated users manage own notes" ON public.notes FOR ALL TO authenticated USING (created_by = auth.uid()) WITH CHECK (created_by = auth.uid());
-- CREATE POLICY "Authenticated users manage own saved searches" ON public.saved_searches FOR ALL TO authenticated USING (created_by = auth.uid()) WITH CHECK (created_by = auth.uid());
-- CREATE POLICY "Authenticated users manage own drawings" ON public.drawings FOR ALL TO authenticated USING (created_by = auth.uid()) WITH CHECK (created_by = auth.uid());
-- CREATE POLICY "Authenticated users manage project sites" ON public.project_sites FOR ALL TO authenticated USING (...);

-- Public read on comps (already applied):
-- CREATE POLICY "Public read comps" ON comps FOR SELECT USING (true);

-- No new SQL required by this audit. All policies verified as functional.
